### PR TITLE
Add first pass of standard_implementation template

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
From https://github.com/metanorma/mn-templates-ogc/issues/12

Hi @ronaldtse ,
- I created this template based on the existing `standard` template and  17-069r3 sample doc (http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_requirements_class_core)
- I noticed that the `standard` template I took guidance from contains both "images" and "figures"  folders. However, in the sample docs, we've been using just "images" folder for figure lodging.  So, I'm a little bit confused about which folder must be used at the end.

I'd really appreciate some feedback from you in this PR,
Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @manuel489 !

> I noticed that the standard template I took guidance from contains both "images" and "figures" folders. However, in the sample docs, we've been using just "images" folder for figure lodging. So, I'm a little bit confused about which folder must be used at the end.

I think "images" folder is fine. Thanks!

**Review by ronaldtse — CHANGES_REQUESTED** [review]
Can you help add the `:comments:` inside the document header for illustration? Thanks!

**Comment by manuelfuenmayor** [comment]
> Can you help add the `:comments:` inside the document header for illustration? Thanks!

I have added some comments to the attributes and used real values taken from 17-069r3 document. Please let me know if I should make any further corrections. Thanks!

**Review by ronaldtse — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
