### PR TITLE
First pass community-standard template

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
From https://github.com/metanorma/mn-templates-ogc/issues/12

This template is based on the *18-053r2* document sample (http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html)
I'd appreciate some feedback in this PR,
Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 thanks. Can you provide comments inside the document attributes with `:comment:` lines so that users know what those attributes are for? Thanks.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
@manuel489 can you help add some `:comments:` to illustrate how to use the attributes? Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 can you help add some `:comments:` to illustrate how to use the attributes? Thanks!

@ronaldtse I have added a comment for every attribute. Please let me know if I should make any further corrections. Thanks!

**Review by ronaldtse — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
